### ISSUE TITLE
Error: Quota exceeded for quota group 'WriteGroup' and limit 'Write requests per user per 100 seconds' of service 'sheets.googleapis.com' for consumer 

### ISSUE THREAD

**Issue by miketaylr** [mozilla/tsci#130]
Apparently, if you try to test something with one domain we go too fast.

```
Updated summary sheet for date 2019/11/17
Cloning current document into document with id: 1ZwJBEDYlCs3MyU_nV4-asiEFD27PILqyBB1eOwFs-hc
(node:35830) UnhandledPromiseRejectionWarning: Error: Quota exceeded for quota group 'WriteGroup' and limit 'Write requests per user per 100 seconds' of service 'sheets.googleapis.com' for consumer 'project_number:1069468129970'.
    at Gaxios.request (/Users/miket/dev/tsci/node_modules/gaxios/build/src/gaxios.js:72:15)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async JWT.requestAsync (/Users/miket/dev/tsci/node_modules/google-auth-library/build/src/auth/oauth2client.js:346:18)
    at async Object.updateTitle (/Users/miket/dev/tsci/spreadsheet.js:766:3)
    at async main (/Users/miket/dev/tsci/index.js:91:5)
(node:35830) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:35830) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by miketaylr** [comment]
I've never seen this before, and it didn't occur just after hitting it. 🤷‍♂
