### ISSUE TITLE
Recover from Bugzilla Gateway Timeout 504

### ISSUE THREAD

**Issue by miketaylr** [mozilla/tsci#81]
It would be cool if we could re-try the Bugzilla query after one times out, rather than just barf.

```
[Symbol(Response internals)]: {
    url: 'https://bugzilla.mozilla.org/rest/bug?include_fields=id,creation_time,see_also,history,priority,product,component,creator&priority=P1&priority=P2&priority=P3&f1=see_also&f2=bug_status&f3=bug_file_loc&o1=anywordssubstr&o2=anywordssubstr&o3=regexp&v1=webcompat.com%2Cgithub.com%2Fwebcompat&v2=UNCONFIRMED%2CNEW%2CASSIGNED%2CREOPENED&v3=https%3F%3A%2F%2F(.%2B%5C.)*tripadvisor%5C.com(%2F.*)*%24&limit=0&api_key=3tR3sh1Aw1KE6FOsASr2Nx8437RcSiOgb6uLNy5m&keywords_type=nowords&keywords=meta%2C%20&status_whiteboard_type=notregexp&status_whiteboard=sci%5C-exclude&emailreporter1=1&emailtype1=notsubstring&email1=%40softvision.ro',
    status: 504,
    statusText: 'GATEWAY_TIMEOUT',
    headers: Headers {
      [Symbol(map)]: [Object: null prototype] {
        'content-length': [ '0' ],
        connection: [ 'Close' ]
      }
    },
    counter: 0
  }
}
(node:5158) UnhandledPromiseRejectionWarning: Error: Bugzilla query failed!
    at /Users/miket/dev/tsci/bugs.js:291:23
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async getDuplicates (/Users/miket/dev/tsci/bugs.js:287:21)
    at async Object.fetchBugs (/Users/miket/dev/tsci/bugs.js:63:13)
    at async main (/Users/miket/dev/tsci/index.js:69:26)
(node:5158) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

```

**Comment by past** [comment]
This code is using `promise-fn-retry`, so it should have retried 3 times and then failed with the error above. Didn't you get the `Retrying buzgilla query...` messages in the console before this?

**Comment by miketaylr** [comment]
> Didn't you get the `Retrying buzgilla query...` messages in the console before this?

Nope;

```
Fetched bug data for site #305: kickstarter.com
Fetched bug data for site #306: google.com.tr
Fetched bug data for site #307: techcrunch.com
Response {
  size: 0,
  timeout: 0,
  [Symbol(Body internals)]: {
    body: PassThrough {
      _readableState: ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: BufferList { head: [Object], tail: [Object], length: 1 },
        length: 166,
        pipes: null,
        pipesCount: 0,
        flowing: null,
        ended: true,
        endEmitted: false,
        reading: false,
        sync: false,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        paused: true,
        emitClose: true,
        autoDestroy: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null
      },
      readable: true,
      _events: [Object: null prototype] {
        prefinish: [Function: prefinish],
        error: [Function]
      },
      _eventsCount: 2,
      _maxListeners: undefined,
      _writableState: WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: true,
        ended: true,
        finished: true,
        destroyed: false,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: true,
        errorEmitted: false,
        emitClose: true,
        autoDestroy: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: {
          next: null,
          entry: null,
          finish: [Function: bound onCorkedFinish]
        }
      },
      writable: false,
      allowHalfOpen: true,
      _transformState: {
        afterTransform: [Function: bound afterTransform],
        needTransform: false,
        transforming: false,
        writecb: null,
        writechunk: null,
        writeencoding: 'buffer'
      }
    },
    disturbed: false,
    error: null
  },
  [Symbol(Response internals)]: {
    url: 'https://bugzilla.mozilla.org/rest/bug?include_fields=id,creation_time,see_also,history,priority,product,component,creator&priority=P1&priority=P2&priority=P3&f1=see_also&f2=bug_status&f3=bug_file_loc&o1=anywordssubstr&o2=anywordssubstr&o3=regexp&v1=webcompat.com%2Cgithub.com%2Fwebcompat&v2=UNCONFIRMED%2CNEW%2CASSIGNED%2CREOPENED&v3=https%3F%3A%2F%2F(.%2B%5C.)*behance%5C.net(%2F.*)*%24&limit=0&api_key=3tR3sh1Aw1KE6FOsASr2Nx8437RcSiOgb6uLNy5m&keywords_type=nowords&keywords=meta%2C%20&status_whiteboard_type=notregexp&status_whiteboard=sci%5C-exclude&emailreporter1=1&emailtype1=notsubstring&email1=%40softvision.ro',
    status: 502,
    statusText: 'Bad Gateway',
    headers: Headers {
      [Symbol(map)]: [Object: null prototype] {
        'content-type': [ 'text/html' ],
        date: [ 'Thu, 04 Jul 2019 17:20:01 GMT' ],
        'content-length': [ '166' ],
        connection: [ 'Close' ]
      }
    },
    counter: 0
  }
}
(node:2920) UnhandledPromiseRejectionWarning: Error: Bugzilla query failed!
    at /Users/miket/dev/tsci/bugs.js:291:23
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async getDuplicates (/Users/miket/dev/tsci/bugs.js:287:21)
    at async Object.fetchBugs (/Users/miket/dev/tsci/bugs.js:63:13)
    at async main (/Users/miket/dev/tsci/index.js:69:26)
(node:2920) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2920) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
